=== Edi013/PHP_Website/Tema3/xml-xsd/factura.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="factura">
	<xs:complexType>
		<xs:sequence>

			<xs:element name="firma">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="nume" type="xs:string"/>
						<xs:element name="sediu" type="xs:string"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>

			<xs:element name="dataCurenta" type="xs:date"/>
			<xs:element name="perioadaFacturareInceput" type="xs:date"/>
			<xs:element name="perioadaFacturareSfarsit" type="xs:date"/>

			<xs:element name="client">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="firstName" type="xs:string"/>
						<xs:element name="lastName" type="xs:string"/>
						<xs:element name="cod" type="xs:string"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			
			<xs:element name="soldPrecedent" type="xs:decimal"/>
			<xs:element name="facturaCurenta" type="xs:decimal"/>
			<xs:element name="tva" type="xs:decimal"/>
			<xs:element name="totalDeAchitat" type="xs:decimal"/>
			<xs:element name="telefonInformatii">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[0-9]{10}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>

		</xs:sequence>
	</xs:complexType>
</xs:element>
</xs:schema>

=== Edi013/PHP_Website/Tema3/xml-xsd/factura.xml
<?xml version="1.0" encoding="UTF-8"?>
<factura xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="factura.xsd">
	<firma>
		<nume>DIGI</nume>
		<sediu>Str. Dr. Staicovici, nr. 75, Forum 2000 Building, Faza I, Et. 2, Sector 5, Bucuresti</sediu>
	</firma>
	<dataCurenta>2023-01-01</dataCurenta>
	<perioadaFacturareInceput>2022-12-01</perioadaFacturareInceput>
	<perioadaFacturareSfarsit>2022-12-30</perioadaFacturareSfarsit>
	<client>
		<firstName>Eduard</firstName>
        <lastName>Ghenea</lastName>
		<cod>12345</cod>
	</client>
	<soldPrecedent>0.00</soldPrecedent>
	<facturaCurenta>72.98</facturaCurenta>
	<tva>13.86</tva>
	<totalDeAchitat>86.84</totalDeAchitat>
	<telefonInformatii>0344400414</telefonInformatii>
</factura>
